name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop, main]

permissions:
  contents: read

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/tests.inc.yml
